version: "3"

services:

  pyspark:
    build: .
    image: codetask
    environment:
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
      JAVA_HOME: /usr/local/openjdk-11
    volumes:
      - ./:/app
      - ./input:/app/input
      - ./output:/app/ouput
      - ./logs:/app/logs    
    depends_on:
      - spark-history-server

  spark-history-server:
    image: gcr.io/spark-operator/spark:v2.4.0
    command: ["/sbin/tini", "-s", "--", "-/opt/spark/bin/spark-class", "-Dspark.history.fs.logDirectory=/logs", "org.apache.spark.deploy.history.HistoryServer"]
    
    volumes:
      - ./logs:/logs



    

    
